name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build and test
        run: ./gradlew check --no-daemon
      - name: Build asciidoctor docs
        if: github.ref == 'refs/heads/main'
        run: ./gradlew asciidoctor --no-daemon
      - name: Upload docs artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/docs/asciidoctor